FROM python:latest
LABEL authors="mattoyudzuru"

WORKDIR /app

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY StudentPerformanceFactors.csv ./

COPY streamlit_app.py ./

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app.py"]